server:
  port: 8081
spring:
  redis:
    host: 127.0.0.1
    post: 6379
    database: 0
    timeout: 1080
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dymtest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#####################################################
#logging:
#  level:
#    root: INFO
#    com.gengdan.demo.mapper: TRACE
#  file:
#    name: /Users/inter.d/logs/test.log
